// src/lib/offices.ts
// Official Nepal Department of Transport Management (DOTM) Office Codes & Directory

export interface TransportOffice {
  code: string
  nameEn: string
  nameNe: string
  locationEn: string
  locationNe: string
  provinceEn: string
  provinceNe: string
  phone?: string
  email?: string
  website?: string
  addressEn: string
  addressNe: string
}

export const TRANSPORT_OFFICES: Record<string, TransportOffice> = {
  '01': {
    code: '01',
    nameEn: 'Transport Management Office (Driver\'s License)',
    nameNe: 'यातायात व्यवस्था कार्यालय (सवारी चालक अनुमतिपत्र)',
    locationEn: 'Ekantakuna, Lalitpur',
    locationNe: 'एकान्तकुना, ललितपुर',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-5527266',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Ekantakuna, Lalitpur, Kathmandu Valley',
    addressNe: 'एकान्तकुना, ललितपुर, काठमाडौं उपत्यका',
  },
  '02': {
    code: '02',
    nameEn: 'TMO Thulo Bharyang (Kathmandu License)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (ठूलोभर्‍याङ)',
    locationEn: 'Thulobharyang, Swayambhu',
    locationNe: 'ठूलोभर्‍याङ, स्वयम्भू, काठमाडौं',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-5249118 / 9851135238',
    email: 'dltmothulo@gmail.com',
    website: 'https://ktmlc1.dotm.gov.np/',
    addressEn: 'Thulobharyang, Swayambhu, Kathmandu',
    addressNe: 'ठूलोभर्‍याङ, स्वयम्भू, काठमाडौं',
  },
  '03': {
    code: '03',
    nameEn: 'TMO Chabahil (Kathmandu License)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (चाबहिल)',
    locationEn: 'Chabahil / Sukedhara',
    locationNe: 'चाबहिल / सुकेधारा, काठमाडौं',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-4569508',
    email: 'info.ktmlc2@dotm.gov.np',
    website: 'https://ktmlc2.dotm.gov.np/',
    addressEn: 'Sukedhara / Chabahil, Kathmandu',
    addressNe: 'सुकेधारा / चाबहिल, काठमाडौं',
  },
  '04': {
    code: '04',
    nameEn: 'TMO Radhe Radhe (Bhaktapur License)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (राधे राधे / जगाती)',
    locationEn: 'Radhe Radhe / Jagati, Bhaktapur',
    locationNe: 'राधे राधे / जगाती, भक्तपुर',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-6637073',
    email: 'info.bhaktapurlc@dotm.gov.np',
    website: 'https://bhaktpurlc.dotm.gov.np/',
    addressEn: 'Radhe Radhe / Jagati, Bhaktapur',
    addressNe: 'राधे राधे / जगाती, भक्तपुर',
  },
  '05': {
    code: '05',
    nameEn: 'TMO Sunsari (Itahari License)',
    nameNe: 'यातायात व्यवस्था कार्यालय (इटहरी)',
    locationEn: 'Itahari, Sunsari',
    locationNe: 'इटहरी, सुनसरी',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '025-476174',
    email: 'info.koshilc@dotm.gov.np',
    website: 'https://sunsarilc.dotm.gov.np/',
    addressEn: 'Itahari Sub-Metropolitan, Sunsari',
    addressNe: 'इटहरी उपमहानगरपालिका, सुनसरी',
  },
  '06': {
    code: '06',
    nameEn: 'Transport Management Office (Pokhara)',
    nameNe: 'यातायात व्यवस्था कार्यालय (पोखरा)',
    locationEn: 'Pokhara, Kaski',
    locationNe: 'पोखरा, कास्की',
    provinceEn: 'Gandaki Province',
    provinceNe: 'गण्डकी प्रदेश',
    phone: '061-460113',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Birauta / Pokhara, Kaski',
    addressNe: 'बिरौटा / पोखरा, कास्की',
  },
  '07': {
    code: '07',
    nameEn: 'Transport Management Office (Butwal)',
    nameNe: 'यातायात व्यवस्था कार्यालय (बुटवल)',
    locationEn: 'Butwal, Rupandehi',
    locationNe: 'बुटवल, रुपन्देही',
    provinceEn: 'Lumbini Province',
    provinceNe: 'लुम्बिनी प्रदेश',
    phone: '071-540134',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Butwal / Driver Training Center, Rupandehi',
    addressNe: 'बुटवल, रुपन्देही',
  },
  '08': {
    code: '08',
    nameEn: 'Transport Management Office (Birgunj)',
    nameNe: 'यातायात व्यवस्था कार्यालय (वीरगन्ज)',
    locationEn: 'Birgunj, Parsa',
    locationNe: 'वीरगन्ज, पर्सा',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    phone: '051-522108',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Birgunj, Parsa',
    addressNe: 'वीरगन्ज, पर्सा',
  },
  '09': {
    code: '09',
    nameEn: 'Transport Management Office (Janakpurdham)',
    nameNe: 'यातायात व्यवस्था कार्यालय (जनकपुरधाम)',
    locationEn: 'Janakpurdham, Dhanusha',
    locationNe: 'जनकपुरधाम, धनुषा',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    phone: '041-520119',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Janakpurdham, Dhanusha',
    addressNe: 'जनकपुरधाम, धनुषा',
  },
  '10': {
    code: '10',
    nameEn: 'TMO Siraha (Lahan)',
    nameNe: 'यातायात व्यवस्था कार्यालय (लहान, सिरहा)',
    locationEn: 'Lahan, Siraha',
    locationNe: 'लहान, सिरहा',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    phone: '033-563217',
    email: 'dotm.sagarmatha1@gmail.com',
    website: 'https://sirahatmo.dotm.gov.np/',
    addressEn: 'Lahan, Siraha',
    addressNe: 'लहान, सिरहा',
  },
  '11': {
    code: '11',
    nameEn: 'TMO Banke (Nepalgunj)',
    nameNe: 'यातायात व्यवस्था कार्यालय (नेपालगन्ज, बाँके)',
    locationEn: 'Nepalgunj, Banke',
    locationNe: 'नेपालगन्ज, बाँके',
    provinceEn: 'Lumbini Province',
    provinceNe: 'लुम्बिनी प्रदेश',
    phone: '081-551487',
    email: 'tmo.bheri@gmail.com',
    website: 'https://bheritmo.dotm.gov.np/',
    addressEn: 'Karkando, Nepalgunj, Banke',
    addressNe: 'कारकाँदो, नेपालगन्ज, बाँके',
  },
  '12': {
    code: '12',
    nameEn: 'TMO Kailali (Dhangadhi)',
    nameNe: 'यातायात व्यवस्था कार्यालय (धनगढी, कैलाली)',
    locationEn: 'Dhangadhi, Kailali',
    locationNe: 'धनगढी, कैलाली',
    provinceEn: 'Sudurpashchim Province',
    provinceNe: 'सुदूरपश्चिम प्रदेश',
    phone: '091-411214',
    email: 'tmoseti13@gmail.com',
    website: 'https://kailalitmo.dotm.gov.np/',
    addressEn: 'Chauraha, Dhangadhi, Kailali',
    addressNe: 'चौराहा, धनगढी, कैलाली',
  },
  '13': {
    code: '13',
    nameEn: 'Transport Management Office (Mahendranagar)',
    nameNe: 'यातायात व्यवस्था कार्यालय (महेन्द्रनगर)',
    locationEn: 'Mahendranagar, Kanchanpur',
    locationNe: 'महेन्द्रनगर, कञ्चनपुर',
    provinceEn: 'Sudurpashchim Province',
    provinceNe: 'सुदूरपश्चिम प्रदेश',
    phone: '099-521234',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Mahendranagar, Kanchanpur',
    addressNe: 'महेन्द्रनगर, कञ्चनपुर',
  },
  '14': {
    code: '14',
    nameEn: 'TMO Dang (Tulsipur)',
    nameNe: 'यातायात व्यवस्था कार्यालय (तुलसीपुर, दाङ)',
    locationEn: 'Tulsipur, Dang',
    locationNe: 'तुलसीपुर, दाङ',
    provinceEn: 'Lumbini Province',
    provinceNe: 'लुम्बिनी प्रदेश',
    phone: '082-520195',
    email: 'Dotmrapti@gmail.com',
    website: 'https://dangtmo.dotm.gov.np/',
    addressEn: 'Tulsipur, Dang',
    addressNe: 'तुलसीपुर, दाङ',
  },
  '15': {
    code: '15',
    nameEn: 'TMO Surkhet (Birendranagar)',
    nameNe: 'यातायात व्यवस्था कार्यालय (सुर्खेत)',
    locationEn: 'Birendranagar, Surkhet',
    locationNe: 'वीरेन्द्रनगर, सुर्खेत',
    provinceEn: 'Karnali Province',
    provinceNe: 'कर्णाली प्रदेश',
    phone: '083-521120',
    email: 'tmo.surkhet022@gmail.com',
    website: 'https://surkhettmo.dotm.gov.np/',
    addressEn: 'Birendranagar, Surkhet',
    addressNe: 'वीरेन्द्रनगर, सुर्खेत',
  },
  '16': {
    code: '16',
    nameEn: 'TMO Jhapa (Birtamod)',
    nameNe: 'यातायात व्यवस्था कार्यालय (बिर्तामोड, झापा)',
    locationEn: 'Birtamode, Jhapa',
    locationNe: 'बिर्तामोड, झापा',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '9852640266',
    email: 'tmo.jhapa@gmail.com',
    website: 'https://jhapatmo.dotm.gov.np/',
    addressEn: 'Birtamode, Jhapa',
    addressNe: 'बिर्तामोड, झापा',
  },
  '17': {
    code: '17',
    nameEn: 'Transport Management Office (Baglung)',
    nameNe: 'यातायात व्यवस्था कार्यालय (बागलुङ)',
    locationEn: 'Baglung',
    locationNe: 'बागलुङ',
    provinceEn: 'Gandaki Province',
    provinceNe: 'गण्डकी प्रदेश',
    phone: '068-520180',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Baglung Bazaar, Baglung',
    addressNe: 'बागलुङ बजार, बागलुङ',
  },
  '18': {
    code: '18',
    nameEn: 'Transport Management Office (Hetauda)',
    nameNe: 'यातायात व्यवस्था कार्यालय (हेटौंडा)',
    locationEn: 'Hetauda, Makwanpur',
    locationNe: 'हेटौंडा, मकवानपुर',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '057-520355',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Hetauda, Makwanpur',
    addressNe: 'हेटौंडा, मकवानपुर',
  },
  '19': {
    code: '19',
    nameEn: 'Transport Management Office (Chitwan)',
    nameNe: 'यातायात व्यवस्था कार्यालय (चितवन)',
    locationEn: 'Bharatpur, Chitwan',
    locationNe: 'भरतपुर, चितवन',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '056-521199',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Bharatpur, Chitwan',
    addressNe: 'भरतपुर, चितवन',
  },
  '20': {
    code: '20',
    nameEn: 'TMO Ilam (Service Office)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (इलाम)',
    locationEn: 'Ilam',
    locationNe: 'इलाम',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '027-524997',
    email: 'info.illlamtmso@dotm.gov.np',
    website: 'https://illamtmso.dotm.gov.np/',
    addressEn: 'Ilam Bazaar, Ilam',
    addressNe: 'इलाम बजार, इलाम',
  },
  '21': {
    code: '21',
    nameEn: 'Transport Management Office (Jumla)',
    nameNe: 'यातायात व्यवस्था कार्यालय (जुम्ला)',
    locationEn: 'Jumla',
    locationNe: 'जुम्ला',
    provinceEn: 'Karnali Province',
    provinceNe: 'कर्णाली प्रदेश',
    phone: '087-520120',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Khalanga, Jumla',
    addressNe: 'खलङ्गा, जुम्ला',
  },
  '22': {
    code: '22',
    nameEn: 'Transport Management Office (Okhaldhunga)',
    nameNe: 'यातायात व्यवस्था कार्यालय (ओखलढुङ्गा)',
    locationEn: 'Okhaldhunga',
    locationNe: 'ओखलढुङ्गा',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '037-520111',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Siddhicharan, Okhaldhunga',
    addressNe: 'सिद्धिचरण, ओखलढुङ्गा',
  },
  '23': {
    code: '23',
    nameEn: 'Transport Management Office (Doti)',
    nameNe: 'यातायात व्यवस्था कार्यालय (डोटी)',
    locationEn: 'Doti',
    locationNe: 'डोटी',
    provinceEn: 'Sudurpashchim Province',
    provinceNe: 'सुदूरपश्चिम प्रदेश',
    phone: '094-420130',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Silgadhi, Doti',
    addressNe: 'सिलगढी, डोटी',
  },
  '24': {
    code: '24',
    nameEn: 'TMO Bara (Kalaiya)',
    nameNe: 'यातायात व्यवस्था कार्यालय (कलैया, बारा)',
    locationEn: 'Kalaiya, Bara',
    locationNe: 'कलैया, बारा',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    phone: '053-590711',
    email: 'tmokalaiya@gmail.com',
    website: 'https://dotm.gov.np',
    addressEn: 'Kalaiya, Bara',
    addressNe: 'कलैया, बारा',
  },
  '25': {
    code: '25',
    nameEn: 'TMO Gurjudhara (Kathmandu Vehicle)',
    nameNe: 'यातायात व्यवस्था कार्यालय (गुर्जुधारा, काठमाडौं)',
    locationEn: 'Gurjudhara, Kathmandu',
    locationNe: 'गुर्जुधारा, काठमाडौं',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-4312311',
    website: 'https://ktmmveh.dotm.gov.np/',
    addressEn: 'Gurjudhara, Chandragiri, Kathmandu',
    addressNe: 'गुर्जुधारा, चन्द्रागिरि, काठमाडौं',
  },
  '26': {
    code: '26',
    nameEn: 'TMSO Bardibas (Mahottari)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (बर्दिबास, महोत्तरी)',
    locationEn: 'Bardibas, Mahottari',
    locationNe: 'बर्दिबास, महोत्तरी',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Bardibas, Mahottari',
    addressNe: 'बर्दिबास, महोत्तरी',
  },
  '27': {
    code: '27',
    nameEn: 'TMSO Kawasoti (Nawalpur)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (कावासोती, नवलपुर)',
    locationEn: 'Kawasoti, Nawalpur',
    locationNe: 'कावासोती, नवलपुर',
    provinceEn: 'Gandaki Province',
    provinceNe: 'गण्डकी प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Kawasoti, Nawalparasi East',
    addressNe: 'कावासोती, नवलपुर',
  },
  '28': {
    code: '28',
    nameEn: 'TMSO Dumre (Tanahun)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (डुम्रे, तनहुँ)',
    locationEn: 'Dumre, Tanahun',
    locationNe: 'डुम्रे, तनहुँ',
    provinceEn: 'Gandaki Province',
    provinceNe: 'गण्डकी प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Bandipur / Dumre, Tanahun',
    addressNe: 'डुम्रे, बन्दीपुर, तनहुँ',
  },
  '29': {
    code: '29',
    nameEn: 'TMSO Gaur (Rautahat)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (गौर, रौतहट)',
    locationEn: 'Gaur, Rautahat',
    locationNe: 'गौर, रौतहट',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Gaur Bazaar, Rautahat',
    addressNe: 'गौर बजार, रौतहट',
  },
  '30': {
    code: '30',
    nameEn: 'TMSO Sarlahi (Malangwa)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (मलङ्गवा, सर्लाही)',
    locationEn: 'Malangwa, Sarlahi',
    locationNe: 'मलङ्गवा, सर्लाही',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Malangwa, Sarlahi',
    addressNe: 'मलङ्गवा, सर्लाही',
  },
  '31': {
    code: '31',
    nameEn: 'TMO Nawalparasi (Parasi)',
    nameNe: 'यातायात व्यवस्था कार्यालय (परासी, नवलपरासी)',
    locationEn: 'Parasi, Nawalparasi West',
    locationNe: 'परासी, नवलपरासी (सुस्ता पश्चिम)',
    provinceEn: 'Lumbini Province',
    provinceNe: 'लुम्बिनी प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Ramgram, Parasi, Nawalparasi West',
    addressNe: 'रामग्राम, परासी, नवलपरासी पश्चिम',
  },
  '32': {
    code: '32',
    nameEn: 'TMSO Palpa (Tansen)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (तानसेन, पाल्पा)',
    locationEn: 'Tansen, Palpa',
    locationNe: 'तानसेन, पाल्पा',
    provinceEn: 'Lumbini Province',
    provinceNe: 'लुम्बिनी प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Tansen Bazaar, Palpa',
    addressNe: 'तानसेन बजार, पाल्पा',
  },
  '33': {
    code: '33',
    nameEn: 'TMSO Banepa (Kavre)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (बनेपा, काभ्रे)',
    locationEn: 'Banepa, Kavrepalanchok',
    locationNe: 'बनेपा, काभ्रेपलाञ्चोक',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Banepa, Kavrepalanchok',
    addressNe: 'बनेपा, काभ्रेपलाञ्चोक',
  },
  '34': {
    code: '34',
    nameEn: 'TMSO Saptari (Rajbiraj)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (राजविराज, सप्तरी)',
    locationEn: 'Rajbiraj, Saptari',
    locationNe: 'राजविराज, सप्तरी',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Rajbiraj, Saptari',
    addressNe: 'राजविराज, सप्तरी',
  },
  '35': {
    code: '35',
    nameEn: 'TMSO Gaighat (Udayapur)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (गाईघाट, उदयपुर)',
    locationEn: 'Gaighat, Udayapur',
    locationNe: 'गाईघाट, उदयपुर',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Gaighat, Triyuga, Udayapur',
    addressNe: 'गाईघाट, त्रियुगा, उदयपुर',
  },
  '36': {
    code: '36',
    nameEn: 'TMSO Dhankuta',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (धनकुटा)',
    locationEn: 'Dhankuta',
    locationNe: 'धनकुटा',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Dhankuta Bazaar, Dhankuta',
    addressNe: 'धनकुटा बजार, धनकुटा',
  },
  '37': {
    code: '37',
    nameEn: 'TMSO Khurkot (Sindhuli)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (खूर्कोट, सिन्धुली)',
    locationEn: 'Khurkot, Sindhuli',
    locationNe: 'खूर्कोट, सिन्धुली',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Khurkot, Golanjor, Sindhuli',
    addressNe: 'खूर्कोट, गोलन्जोर, सिन्धुली',
  },
  '38': {
    code: '38',
    nameEn: 'TMSO Dadeldhura',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (डडेल्धुरा)',
    locationEn: 'Dadeldhura',
    locationNe: 'डडेल्धुरा',
    provinceEn: 'Sudurpashchim Province',
    provinceNe: 'सुदूरपश्चिम प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Amargadhi, Dadeldhura',
    addressNe: 'अमरगढी, डडेल्धुरा',
  },
  '39': {
    code: '39',
    nameEn: 'TMSO Rukum (Musikot)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (रुकुम)',
    locationEn: 'Musikot, Rukum West',
    locationNe: 'मुसिकोट, रुकुम पश्चिम',
    provinceEn: 'Karnali Province',
    provinceNe: 'कर्णाली प्रदेश',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Musikot, Rukum West',
    addressNe: 'मुसिकोट, रुकुम पश्चिम',
  },
}

/**
 * Match a raw office name or code from the database record (e.g. "JHAPA", "Thulobharyang",
 * "RADHERADHE", "KALAIYA", "ITAHARI") to the verified TransportOffice directory entry.
 */
export function getTransportOfficeByOfficeName(rawOffice?: string | null): TransportOffice | null {
  if (!rawOffice) return null
  const cleaned = rawOffice.trim().toUpperCase()
  if (!cleaned || cleaned === 'UNKNOWN' || cleaned === 'DOTM') return null

  // 1. Direct code lookup if numeric
  if (TRANSPORT_OFFICES[cleaned]) return TRANSPORT_OFFICES[cleaned]

  // 2. Canonical mapping of database office values to office codes
  const aliasToCode: Record<string, string> = {
    JHAPA: '16',
    BIRTAMOD: '16',
    BIRTAMODE: '16',
    THULOBHARYANG: '02',
    'THULO BHARYANG': '02',
    SWAYAMBHU: '02',
    CHABAHIL: '03',
    SUKEDHARA: '03',
    RADHERADHE: '04',
    'RADHE RADHE': '04',
    JAGATI: '04',
    BHAKTAPUR: '04',
    ITAHARI: '05',
    SUNSARI: '05',
    POKHARA: '06',
    KASKI: '06',
    BUTWAL: '07',
    RUPANDEHI: '07',
    BIRGUNJ: '08',
    PARSA: '08',
    JANAKPUR: '09',
    JANAKPURDHAM: '09',
    DHANUSHA: '09',
    LAHAN: '10',
    SIRAHA: '10',
    NEPALGUNJ: '11',
    BANKE: '11',
    DHANGADI: '12',
    DHANGADHI: '12',
    KAILALI: '12',
    KANCHANPUR: '13',
    MAHENDRANAGAR: '13',
    DANG: '14',
    TULSIPUR: '14',
    SURKHET: '15',
    BIRENDRANAGAR: '15',
    BAGLUNG: '17',
    HETAUDA: '18',
    MAKWANPUR: '18',
    CHITWAN: '19',
    BHARATPUR: '19',
    ILLAM: '20',
    ILAM: '20',
    JUMLA: '21',
    OKHALDHUNGA: '22',
    DOTI: '23',
    DIPAYAL: '23',
    SILGADHI: '23',
    KALAIYA: '24',
    BARA: '24',
    GURJUDHARA: '25',
    EKANTAKUNA: '01',
    LALITPUR: '01',
    BARDIBAS: '26',
    MAHOTTARI: '26',
    KAWASOTI: '27',
    NAWALPUR: '27',
    DUMRE: '28',
    TANAHUN: '28',
    GAUR: '29',
    RAUTAHAT: '29',
    SARLAHI: '30',
    MALANGWA: '30',
    NAWALPARASI: '31',
    PARASI: '31',
    PALPA: '32',
    TANSEN: '32',
    BANEPA: '33',
    KAVRE: '33',
    KAVREPALANCHOK: '33',
    SAPTARI: '34',
    RAJBIRAJ: '34',
    GAIGHAT: '35',
    UDAYAPUR: '35',
    DHANKUTA: '36',
    KHURKOT: '37',
    SINDHULI: '37',
    DADELDHURA: '38',
    RUKUM: '39',
  }

  const mappedCode = aliasToCode[cleaned]
  if (mappedCode && TRANSPORT_OFFICES[mappedCode]) {
    return TRANSPORT_OFFICES[mappedCode]
  }

  // 3. Fallback: fuzzy/partial match on alias
  for (const [alias, code] of Object.entries(aliasToCode)) {
    if (cleaned.includes(alias) || alias.includes(cleaned)) {
      if (TRANSPORT_OFFICES[code]) return TRANSPORT_OFFICES[code]
    }
  }

  // 4. Fallback: search in English name or location
  for (const office of Object.values(TRANSPORT_OFFICES)) {
    if (
      office.nameEn.toUpperCase().includes(cleaned) ||
      office.locationEn.toUpperCase().includes(cleaned) ||
      cleaned.includes(office.locationEn.toUpperCase())
    ) {
      return office
    }
  }

  return null
}

/**
 * Kept for backwards compatibility. Note: In Nepal, the license number prefix (e.g. "01-01-")
 * does not uniquely identify the issuing transport office; the issuing office is stored in the
 * database record (see getTransportOfficeByOfficeName).
 */
export function getTransportOfficeByLicense(_licenseNumber?: string): TransportOffice | null {
  void _licenseNumber
  return null
}

export function getAllTransportOffices(): TransportOffice[] {
  return Object.values(TRANSPORT_OFFICES).sort((a, b) => Number(a.code) - Number(b.code))
}
