// src/lib/offices.ts
// Official Nepal Department of Transport Management (DOTM) Office Codes & Directory

export interface TransportOffice {
  code: string
  nameEn: string
  nameNe: string
  locationEn: string
  locationNe: string
  provinceEn: string
  provinceNe: string
  phone?: string
  email?: string
  website?: string
  addressEn: string
  addressNe: string
}

export const TRANSPORT_OFFICES: Record<string, TransportOffice> = {
  '01': {
    code: '01',
    nameEn: 'Transport Management Office (Driver\'s License)',
    nameNe: 'यातायात व्यवस्था कार्यालय (सवारी चालक अनुमतिपत्र)',
    locationEn: 'Ekantakuna, Lalitpur',
    locationNe: 'एकान्तकुना, ललितपुर',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-5527266',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Ekantakuna, Lalitpur, Kathmandu Valley',
    addressNe: 'एकान्तकुना, ललितपुर, काठमाडौं उपत्यका',
  },
  '02': {
    code: '02',
    nameEn: 'TMO Thulo Bharyang (Kathmandu License)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (ठूलोभर्‍याङ)',
    locationEn: 'Thulobharyang, Swayambhu',
    locationNe: 'ठूलोभर्‍याङ, स्वयम्भू, काठमाडौं',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-5249118 / 9851135238',
    email: 'dltmothulo@gmail.com',
    website: 'https://ktmlc1.dotm.gov.np/',
    addressEn: 'Thulobharyang, Swayambhu, Kathmandu',
    addressNe: 'ठूलोभर्‍याङ, स्वयम्भू, काठमाडौं',
  },
  '03': {
    code: '03',
    nameEn: 'TMO Chabahil (Kathmandu License)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (चाबहिल)',
    locationEn: 'Chabahil / Sukedhara',
    locationNe: 'चाबहिल / सुकेधारा, काठमाडौं',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-4569508',
    email: 'info.ktmlc2@dotm.gov.np',
    website: 'https://ktmlc2.dotm.gov.np/',
    addressEn: 'Sukedhara / Chabahil, Kathmandu',
    addressNe: 'सुकेधारा / चाबहिल, काठमाडौं',
  },
  '04': {
    code: '04',
    nameEn: 'TMO Radhe Radhe (Bhaktapur License)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (राधे राधे / जगाती)',
    locationEn: 'Radhe Radhe / Jagati, Bhaktapur',
    locationNe: 'राधे राधे / जगाती, भक्तपुर',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-6637073',
    email: 'info.bhaktapurlc@dotm.gov.np',
    website: 'https://bhaktpurlc.dotm.gov.np/',
    addressEn: 'Radhe Radhe / Jagati, Bhaktapur',
    addressNe: 'राधे राधे / जगाती, भक्तपुर',
  },
  '05': {
    code: '05',
    nameEn: 'TMO Sunsari (Itahari License)',
    nameNe: 'यातायात व्यवस्था कार्यालय (इटहरी)',
    locationEn: 'Itahari, Sunsari',
    locationNe: 'इटहरी, सुनसरी',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '025-476174',
    email: 'info.koshilc@dotm.gov.np',
    website: 'https://sunsarilc.dotm.gov.np/',
    addressEn: 'Itahari Sub-Metropolitan, Sunsari',
    addressNe: 'इटहरी उपमहानगरपालिका, सुनसरी',
  },
  '06': {
    code: '06',
    nameEn: 'Transport Management Office (Pokhara)',
    nameNe: 'यातायात व्यवस्था कार्यालय (पोखरा)',
    locationEn: 'Pokhara, Kaski',
    locationNe: 'पोखरा, कास्की',
    provinceEn: 'Gandaki Province',
    provinceNe: 'गण्डकी प्रदेश',
    phone: '061-460113',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Birauta / Pokhara, Kaski',
    addressNe: 'बिरौटा / पोखरा, कास्की',
  },
  '07': {
    code: '07',
    nameEn: 'Transport Management Office (Butwal)',
    nameNe: 'यातायात व्यवस्था कार्यालय (बुटवल)',
    locationEn: 'Butwal, Rupandehi',
    locationNe: 'बुटवल, रुपन्देही',
    provinceEn: 'Lumbini Province',
    provinceNe: 'लुम्बिनी प्रदेश',
    phone: '071-540134',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Butwal / Driver Training Center, Rupandehi',
    addressNe: 'बुटवल, रुपन्देही',
  },
  '08': {
    code: '08',
    nameEn: 'Transport Management Office (Birgunj)',
    nameNe: 'यातायात व्यवस्था कार्यालय (वीरगन्ज)',
    locationEn: 'Birgunj, Parsa',
    locationNe: 'वीरगन्ज, पर्सा',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    phone: '051-522108',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Birgunj, Parsa',
    addressNe: 'वीरगन्ज, पर्सा',
  },
  '09': {
    code: '09',
    nameEn: 'Transport Management Office (Janakpurdham)',
    nameNe: 'यातायात व्यवस्था कार्यालय (जनकपुरधाम)',
    locationEn: 'Janakpurdham, Dhanusha',
    locationNe: 'जनकपुरधाम, धनुषा',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    phone: '041-520119',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Janakpurdham, Dhanusha',
    addressNe: 'जनकपुरधाम, धनुषा',
  },
  '10': {
    code: '10',
    nameEn: 'TMO Siraha (Lahan)',
    nameNe: 'यातायात व्यवस्था कार्यालय (लहान, सिरहा)',
    locationEn: 'Lahan, Siraha',
    locationNe: 'लहान, सिरहा',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    phone: '033-563217',
    email: 'dotm.sagarmatha1@gmail.com',
    website: 'https://sirahatmo.dotm.gov.np/',
    addressEn: 'Lahan, Siraha',
    addressNe: 'लहान, सिरहा',
  },
  '11': {
    code: '11',
    nameEn: 'TMO Banke (Nepalgunj)',
    nameNe: 'यातायात व्यवस्था कार्यालय (नेपालगन्ज, बाँके)',
    locationEn: 'Nepalgunj, Banke',
    locationNe: 'नेपालगन्ज, बाँके',
    provinceEn: 'Lumbini Province',
    provinceNe: 'लुम्बिनी प्रदेश',
    phone: '081-551487',
    email: 'tmo.bheri@gmail.com',
    website: 'https://bheritmo.dotm.gov.np/',
    addressEn: 'Karkando, Nepalgunj, Banke',
    addressNe: 'कारकाँदो, नेपालगन्ज, बाँके',
  },
  '12': {
    code: '12',
    nameEn: 'TMO Kailali (Dhangadhi)',
    nameNe: 'यातायात व्यवस्था कार्यालय (धनगढी, कैलाली)',
    locationEn: 'Dhangadhi, Kailali',
    locationNe: 'धनगढी, कैलाली',
    provinceEn: 'Sudurpashchim Province',
    provinceNe: 'सुदूरपश्चिम प्रदेश',
    phone: '091-411214',
    email: 'tmoseti13@gmail.com',
    website: 'https://kailalitmo.dotm.gov.np/',
    addressEn: 'Chauraha, Dhangadhi, Kailali',
    addressNe: 'चौराहा, धनगढी, कैलाली',
  },
  '13': {
    code: '13',
    nameEn: 'Transport Management Office (Mahendranagar)',
    nameNe: 'यातायात व्यवस्था कार्यालय (महेन्द्रनगर)',
    locationEn: 'Mahendranagar, Kanchanpur',
    locationNe: 'महेन्द्रनगर, कञ्चनपुर',
    provinceEn: 'Sudurpashchim Province',
    provinceNe: 'सुदूरपश्चिम प्रदेश',
    phone: '099-521234',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Mahendranagar, Kanchanpur',
    addressNe: 'महेन्द्रनगर, कञ्चनपुर',
  },
  '14': {
    code: '14',
    nameEn: 'TMO Dang (Tulsipur)',
    nameNe: 'यातायात व्यवस्था कार्यालय (तुलसीपुर, दाङ)',
    locationEn: 'Tulsipur, Dang',
    locationNe: 'तुलसीपुर, दाङ',
    provinceEn: 'Lumbini Province',
    provinceNe: 'लुम्बिनी प्रदेश',
    phone: '082-520195',
    email: 'Dotmrapti@gmail.com',
    website: 'https://dangtmo.dotm.gov.np/',
    addressEn: 'Tulsipur, Dang',
    addressNe: 'तुलसीपुर, दाङ',
  },
  '15': {
    code: '15',
    nameEn: 'TMO Surkhet (Birendranagar)',
    nameNe: 'यातायात व्यवस्था कार्यालय (सुर्खेत)',
    locationEn: 'Birendranagar, Surkhet',
    locationNe: 'वीरेन्द्रनगर, सुर्खेत',
    provinceEn: 'Karnali Province',
    provinceNe: 'कर्णाली प्रदेश',
    phone: '083-521120',
    email: 'tmo.surkhet022@gmail.com',
    website: 'https://surkhettmo.dotm.gov.np/',
    addressEn: 'Birendranagar, Surkhet',
    addressNe: 'वीरेन्द्रनगर, सुर्खेत',
  },
  '16': {
    code: '16',
    nameEn: 'TMO Jhapa (Birtamod)',
    nameNe: 'यातायात व्यवस्था कार्यालय (बिर्तामोड, झापा)',
    locationEn: 'Birtamode, Jhapa',
    locationNe: 'बिर्तामोड, झापा',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '9852640266',
    email: 'tmo.jhapa@gmail.com',
    website: 'https://jhapatmo.dotm.gov.np/',
    addressEn: 'Birtamode, Jhapa',
    addressNe: 'बिर्तामोड, झापा',
  },
  '17': {
    code: '17',
    nameEn: 'Transport Management Office (Baglung)',
    nameNe: 'यातायात व्यवस्था कार्यालय (बागलुङ)',
    locationEn: 'Baglung',
    locationNe: 'बागलुङ',
    provinceEn: 'Gandaki Province',
    provinceNe: 'गण्डकी प्रदेश',
    phone: '068-520180',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Baglung Bazaar, Baglung',
    addressNe: 'बागलुङ बजार, बागलुङ',
  },
  '18': {
    code: '18',
    nameEn: 'Transport Management Office (Hetauda)',
    nameNe: 'यातायात व्यवस्था कार्यालय (हेटौंडा)',
    locationEn: 'Hetauda, Makwanpur',
    locationNe: 'हेटौंडा, मकवानपुर',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '057-520355',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Hetauda, Makwanpur',
    addressNe: 'हेटौंडा, मकवानपुर',
  },
  '19': {
    code: '19',
    nameEn: 'Transport Management Office (Chitwan)',
    nameNe: 'यातायात व्यवस्था कार्यालय (चितवन)',
    locationEn: 'Bharatpur, Chitwan',
    locationNe: 'भरतपुर, चितवन',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '056-521199',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Bharatpur, Chitwan',
    addressNe: 'भरतपुर, चितवन',
  },
  '20': {
    code: '20',
    nameEn: 'TMO Ilam (Service Office)',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय (इलाम)',
    locationEn: 'Ilam',
    locationNe: 'इलाम',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '027-524997',
    email: 'info.illlamtmso@dotm.gov.np',
    website: 'https://illamtmso.dotm.gov.np/',
    addressEn: 'Ilam Bazaar, Ilam',
    addressNe: 'इलाम बजार, इलाम',
  },
  '21': {
    code: '21',
    nameEn: 'Transport Management Office (Jumla)',
    nameNe: 'यातायात व्यवस्था कार्यालय (जुम्ला)',
    locationEn: 'Jumla',
    locationNe: 'जुम्ला',
    provinceEn: 'Karnali Province',
    provinceNe: 'कर्णाली प्रदेश',
    phone: '087-520120',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Khalanga, Jumla',
    addressNe: 'खलङ्गा, जुम्ला',
  },
  '22': {
    code: '22',
    nameEn: 'Transport Management Office (Okhaldhunga)',
    nameNe: 'यातायात व्यवस्था कार्यालय (ओखलढुङ्गा)',
    locationEn: 'Okhaldhunga',
    locationNe: 'ओखलढुङ्गा',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '037-520111',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Siddhicharan, Okhaldhunga',
    addressNe: 'सिद्धिचरण, ओखलढुङ्गा',
  },
  '23': {
    code: '23',
    nameEn: 'Transport Management Office (Doti)',
    nameNe: 'यातायात व्यवस्था कार्यालय (डोटी)',
    locationEn: 'Doti',
    locationNe: 'डोटी',
    provinceEn: 'Sudurpashchim Province',
    provinceNe: 'सुदूरपश्चिम प्रदेश',
    phone: '094-420130',
    email: 'info@dotm.gov.np',
    website: 'https://dotm.gov.np',
    addressEn: 'Silgadhi, Doti',
    addressNe: 'सिलगढी, डोटी',
  },
  '24': {
    code: '24',
    nameEn: 'TMO Bara (Kalaiya)',
    nameNe: 'यातायात व्यवस्था कार्यालय (कलैया, बारा)',
    locationEn: 'Kalaiya, Bara',
    locationNe: 'कलैया, बारा',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    phone: '053-590711',
    email: 'tmokalaiya@gmail.com',
    website: 'https://dotm.gov.np',
    addressEn: 'Kalaiya, Bara',
    addressNe: 'कलैया, बारा',
  },
  '25': {
    code: '25',
    nameEn: 'TMO Gurjudhara (Kathmandu Vehicle)',
    nameNe: 'यातायात व्यवस्था कार्यालय (गुर्जुधारा, काठमाडौं)',
    locationEn: 'Gurjudhara, Kathmandu',
    locationNe: 'गुर्जुधारा, काठमाडौं',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-4312311',
    website: 'https://ktmmveh.dotm.gov.np/',
    addressEn: 'Gurjudhara, Chandragiri, Kathmandu',
    addressNe: 'गुर्जुधारा, चन्द्रागिरि, काठमाडौं',
  },
}

/**
 * Given a license number (e.g. "01-01-12345678"), extract the first 2 digits
 * and return the matching transport office if known.
 */
export function getTransportOfficeByLicense(licenseNumber: string): TransportOffice | null {
  if (!licenseNumber) return null
  const code = licenseNumber.slice(0, 2)
  return TRANSPORT_OFFICES[code] || null
}

export function getAllTransportOffices(): TransportOffice[] {
  return Object.values(TRANSPORT_OFFICES).sort((a, b) => Number(a.code) - Number(b.code))
}
