// src/lib/offices.ts
// Official Nepal Department of Transport Management (DOTM) Office Codes & Directory

export interface TransportOffice {
  code: string
  nameEn: string
  nameNe: string
  locationEn: string
  locationNe: string
  provinceEn: string
  provinceNe: string
  phone?: string
  addressEn: string
  addressNe: string
}

export const TRANSPORT_OFFICES: Record<string, TransportOffice> = {
  '01': {
    code: '01',
    nameEn: 'Transport Management Office (Driver\'s License)',
    nameNe: 'यातायात व्यवस्था कार्यालय (सवारी चालक अनुमतिपत्र)',
    locationEn: 'Ekantakuna, Lalitpur',
    locationNe: 'एकान्तकुना, ललितपुर',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-5527266',
    addressEn: 'Ekantakuna, Lalitpur, Kathmandu Valley',
    addressNe: 'एकान्तकुना, ललितपुर, काठमाडौं उपत्यका',
  },
  '02': {
    code: '02',
    nameEn: 'Transport Management Service Office',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय',
    locationEn: 'Thulobharyang, Swayambhu',
    locationNe: 'ठूलोभर्‍याङ, स्वयम्भू, काठमाडौं',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-4033706',
    addressEn: 'Thulobharyang, Swayambhu, Kathmandu',
    addressNe: 'ठूलोभर्‍याङ, स्वयम्भू, काठमाडौं',
  },
  '03': {
    code: '03',
    nameEn: 'Transport Management Service Office',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय',
    locationEn: 'Chabahil / Sukedhara',
    locationNe: 'चाबहिल / सुकेधारा, काठमाडौं',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-4378850',
    addressEn: 'Sukedhara / Chabahil, Kathmandu',
    addressNe: 'सुकेधारा / चाबहिल, काठमाडौं',
  },
  '04': {
    code: '04',
    nameEn: 'Transport Management Service Office',
    nameNe: 'यातायात व्यवस्था सेवा कार्यालय',
    locationEn: 'Jagati, Bhaktapur',
    locationNe: 'जगाती, भक्तपुर',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '01-6617307',
    addressEn: 'Jagati, Bhaktapur',
    addressNe: 'जगाती, भक्तपुर',
  },
  '05': {
    code: '05',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Itahari, Sunsari',
    locationNe: 'इटहरी, सुनसरी',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '025-580199',
    addressEn: 'Itahari Sub-Metropolitan, Sunsari',
    addressNe: 'इटहरी उपमहानगरपालिका, सुनसरी',
  },
  '06': {
    code: '06',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Pokhara, Kaski',
    locationNe: 'पोखरा, कास्की',
    provinceEn: 'Gandaki Province',
    provinceNe: 'गण्डकी प्रदेश',
    phone: '061-460113',
    addressEn: 'Birauta / Pokhara, Kaski',
    addressNe: 'बिरौटा / पोखरा, कास्की',
  },
  '07': {
    code: '07',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Butwal, Rupandehi',
    locationNe: 'बुटवल, रुपन्देही',
    provinceEn: 'Lumbini Province',
    provinceNe: 'लुम्बिनी प्रदेश',
    phone: '071-540134',
    addressEn: 'Butwal / Driver Training Center, Rupandehi',
    addressNe: 'बुटवल, रुपन्देही',
  },
  '08': {
    code: '08',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Birgunj, Parsa',
    locationNe: 'वीरगन्ज, पर्सा',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    phone: '051-522108',
    addressEn: 'Birgunj, Parsa',
    addressNe: 'वीरगन्ज, पर्सा',
  },
  '09': {
    code: '09',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Janakpurdham, Dhanusha',
    locationNe: 'जनकपुरधाम, धनुषा',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    phone: '041-520119',
    addressEn: 'Janakpurdham, Dhanusha',
    addressNe: 'जनकपुरधाम, धनुषा',
  },
  '10': {
    code: '10',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Lahan, Siraha',
    locationNe: 'लहान, सिरहा',
    provinceEn: 'Madhesh Province',
    provinceNe: 'मधेश प्रदेश',
    phone: '033-560171',
    addressEn: 'Lahan, Siraha',
    addressNe: 'लहान, सिरहा',
  },
  '11': {
    code: '11',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Nepalgunj, Banke',
    locationNe: 'नेपालगन्ज, बाँके',
    provinceEn: 'Lumbini Province',
    provinceNe: 'लुम्बिनी प्रदेश',
    phone: '081-520188',
    addressEn: 'Karkando, Nepalgunj, Banke',
    addressNe: 'कारकाँदो, नेपालगन्ज, बाँके',
  },
  '12': {
    code: '12',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Dhangadhi, Kailali',
    locationNe: 'धनगढी, कैलाली',
    provinceEn: 'Sudurpashchim Province',
    provinceNe: 'सुदूरपश्चिम प्रदेश',
    phone: '091-521199',
    addressEn: 'Chauraha, Dhangadhi, Kailali',
    addressNe: 'चौराहा, धनगढी, कैलाली',
  },
  '13': {
    code: '13',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Mahendranagar, Kanchanpur',
    locationNe: 'महेन्द्रनगर, कञ्चनपुर',
    provinceEn: 'Sudurpashchim Province',
    provinceNe: 'सुदूरपश्चिम प्रदेश',
    phone: '099-521234',
    addressEn: 'Mahendranagar, Kanchanpur',
    addressNe: 'महेन्द्रनगर, कञ्चनपुर',
  },
  '14': {
    code: '14',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Tulsipur, Dang',
    locationNe: 'तुलसीपुर, दाङ',
    provinceEn: 'Lumbini Province',
    provinceNe: 'लुम्बिनी प्रदेश',
    phone: '082-520145',
    addressEn: 'Tulsipur, Dang',
    addressNe: 'तुलसीपुर, दाङ',
  },
  '15': {
    code: '15',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Birendranagar, Surkhet',
    locationNe: 'वीरेन्द्रनगर, सुर्खेत',
    provinceEn: 'Karnali Province',
    provinceNe: 'कर्णाली प्रदेश',
    phone: '083-520133',
    addressEn: 'Birendranagar, Surkhet',
    addressNe: 'वीरेन्द्रनगर, सुर्खेत',
  },
  '16': {
    code: '16',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Birtamode, Jhapa',
    locationNe: 'बिर्तामोड, झापा',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '023-540199',
    addressEn: 'Birtamode, Jhapa',
    addressNe: 'बिर्तामोड, झापा',
  },
  '17': {
    code: '17',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Baglung',
    locationNe: 'बागलुङ',
    provinceEn: 'Gandaki Province',
    provinceNe: 'गण्डकी प्रदेश',
    phone: '068-520180',
    addressEn: 'Baglung Bazaar, Baglung',
    addressNe: 'बागलुङ बजार, बागलुङ',
  },
  '18': {
    code: '18',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Hetauda, Makwanpur',
    locationNe: 'हेटौंडा, मकवानपुर',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '057-520355',
    addressEn: 'Hetauda, Makwanpur',
    addressNe: 'हेटौंडा, मकवानपुर',
  },
  '19': {
    code: '19',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Bharatpur, Chitwan',
    locationNe: 'भरतपुर, चितवन',
    provinceEn: 'Bagmati Province',
    provinceNe: 'बागमती प्रदेश',
    phone: '056-521199',
    addressEn: 'Bharatpur, Chitwan',
    addressNe: 'भरतपुर, चितवन',
  },
  '20': {
    code: '20',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Ilam',
    locationNe: 'इलाम',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '027-520155',
    addressEn: 'Ilam Bazaar, Ilam',
    addressNe: 'इलाम बजार, इलाम',
  },
  '21': {
    code: '21',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Jumla',
    locationNe: 'जुम्ला',
    provinceEn: 'Karnali Province',
    provinceNe: 'कर्णाली प्रदेश',
    phone: '087-520120',
    addressEn: 'Khalanga, Jumla',
    addressNe: 'खलङ्गा, जुम्ला',
  },
  '22': {
    code: '22',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Okhaldhunga',
    locationNe: 'ओखलढुङ्गा',
    provinceEn: 'Koshi Province',
    provinceNe: 'कोशी प्रदेश',
    phone: '037-520111',
    addressEn: 'Siddhicharan, Okhaldhunga',
    addressNe: 'सिद्धिचरण, ओखलढुङ्गा',
  },
  '23': {
    code: '23',
    nameEn: 'Transport Management Office',
    nameNe: 'यातायात व्यवस्था कार्यालय',
    locationEn: 'Doti',
    locationNe: 'डोटी',
    provinceEn: 'Sudurpashchim Province',
    provinceNe: 'सुदूरपश्चिम प्रदेश',
    phone: '094-420130',
    addressEn: 'Silgadhi, Doti',
    addressNe: 'सिलगढी, डोटी',
  },
}

/**
 * Given a license number (e.g. "01-01-12345678"), extract the first 2 digits
 * and return the matching transport office if known.
 */
export function getTransportOfficeByLicense(licenseNumber: string): TransportOffice | null {
  if (!licenseNumber) return null
  const code = licenseNumber.slice(0, 2)
  return TRANSPORT_OFFICES[code] || null
}

export function getAllTransportOffices(): TransportOffice[] {
  return Object.values(TRANSPORT_OFFICES)
}
